# Generated by Django 2.0.5 on 2018-05-09 03:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session',
            field=models.UUIDField(default=uuid.UUID('7775c9f4-9f90-41ac-82d0-0c2a7b509fa3')),
        ),
    ]
