# Generated by Django 2.0.5 on 2018-05-09 01:29

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='session',
            field=models.UUIDField(default=uuid.UUID('9d097516-08ad-47ca-bb00-5c9c9e2ab035')),
        ),
    ]
